### ISSUE TITLE
Android 15 Support

### ISSUE THREAD

**Issue by pr4bh4sh** [DeviceFarmer/STFService.apk#146]
App doesn't work on Android 15 beta. I know the it's not out of beta yet but any change to get Android 15 support please.
```
adb shell am startservice --user 0 \
    -a jp.co.cyberagent.stf.ACTION_START \
    -n jp.co.cyberagent.stf/.Service
Starting service: Intent { act=jp.co.cyberagent.stf.ACTION_START cmp=jp.co.cyberagent.stf/.Service }
Error: app is in background uid null
```

**Comment by denis99999** [comment]
@pr4bh4sh , try to replace `startservice` by `start-foreground-service`

**Comment by pr4bh4sh** [comment]
Thanks, it worked. I also updated latest docker image, works fine with Android 15 beta pixels.

**Comment by myfortest2** [comment]
its not working 
: 2024-11-13T15:16:37.692Z INF/device:plugins:service 2890001 [uweqrswkdynj55kj] using 'start-foreground-service' command for API 30
: 2024-11-13T15:16:37.702Z INF/device:plugins:service 2890001 [uweqrswkdynj55kj] Agent says: "InputClient started"
: 2024-11-13T15:16:37.748Z FTL/device 2890001 [uweqrswkdynj55kj] Setup had an error Error: Service had an error: "Error: Not found; no service started."
:     at openstf/lib/units/device/plugins/service.js:104:23
: From previous event:
:     at openstf/lib/units/device/plugins/service.js:79:14
:     at processImmediate (internal/timers.js:462:21)
: 2024-11-13T15:16:37.749Z FTL/util:lifecycle 2890001 [uweqrswkdynj55kj] Shutting down due to fatal error
